<a href="https://colab.research.google.com/github/Menon-Vineet/Python-Basics-Simpli-/blob/main/Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [155]:
import pandas as pd

In [156]:
def add2(a,b):
    return a+b

In [157]:
a=1.2
b=3.5
add2(a,b)


4.7

In [158]:
w = "Vineet"
"et" in w

True

In [159]:
q=(1,2,)

In [160]:
q=q*2

In [161]:
q

(1, 2, 1, 2)

In [162]:
def p():
  q=1
  w=2
  return q,w

In [163]:
p()

(1, 2)

In [164]:
s=("q","w",'e')

In [165]:
for position, name in enumerate(s):
  print (position+1, name)

1 q
2 w
3 e


In [166]:
sorted ("Vineet Menon")

[' ', 'M', 'V', 'e', 'e', 'e', 'i', 'n', 'n', 'n', 'o', 't']

In [167]:
Score = 50

In [168]:
if Score>90:
  print ("Grade A")
elif (90>=Score>=50):
  print ('Grade B')
else:
  print ("Fail")

Grade B


In [169]:
import numpy as np
ar = np.zeros((4,4))

In [170]:
ar

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [171]:
print (ar)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [172]:
ara = np.arange(4)

In [173]:
ara

array([0, 1, 2, 3])

In [174]:
arr = np.linspace(1,6,5)

In [175]:
arr

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

In [176]:
td = np.arange(27).reshape(3,3,3)

In [177]:
td

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [178]:
td.ndim

3

In [179]:
td.shape

(3, 3, 3)

In [180]:
td.size

27

In [181]:
td.dtype

dtype('int64')

In [182]:
import numpy as np


In [183]:
countries = np.array(['Algeria','Angola','Argentina','Australia','Austria','Bahamas','Bangladesh','Belarus','Belgium','Bhutan','Brazil','Bulgaria','Cambodia','Cameroon','Chile','China','Colombia','Cyprus','Denmark','El Salvador','Estonia','Ethiopia','Fiji','Finland','France','Georgia','Ghana','Grenada','Guinea','Haiti','Honduras','Hungary','India','Indonesia','Ireland','Italy','Japan','Kenya', 'South Korea','Liberia','Malaysia','Mexico', 'Morocco','Nepal','New Zealand','Norway','Pakistan', 'Peru','Qatar','Russia','Singapore','South Africa','Spain','Sweden','Switzerland','Thailand', 'United Arab Emirates','United Kingdom','United States','Uruguay','Venezuela','Vietnam','Zimbabwe'])

In [184]:
GPC = np.array([2255.225482,629.9553062,11601.63022,25306.82494,27266.40335,19466.99052,588.3691778,2890.345675,24733.62696,1445.760002,4803.398244,2618.876037,590.4521124,665.7982328,7122.938458,2639.54156,3362.4656,15378.16704,30860.12808,2579.115607,6525.541272,229.6769525,2242.689259,27570.4852,23016.84778,1334.646773,402.6953275,6047.200797,394.1156638,385.5793827,1414.072488,5745.981529,837.7464011,1206.991065,27715.52837,18937.24998,39578.07441,478.2194906,16684.21278,279.2204061,5345.213415,6288.25324,1908.304416,274.8728621,14646.42094,40034.85063,672.1547506,3359.517402,36152.66676,3054.727742,33529.83052,3825.093781,15428.32098,33630.24604,39170.41371,2699.123242,21058.43643,28272.40661,37691.02733,9581.05659,5671.912202,757.4009286,347.7456605])

In [185]:
maxGPC = GPC.argmax()

In [186]:
CmaxGPC = countries[maxGPC]

In [187]:
CmaxGPC

'Norway'

In [188]:
minGPC = GPC.argmin()

In [189]:
CminGPC = countries[minGPC]

In [190]:
CminGPC

'Ethiopia'

In [191]:
for country in countries:
  print ("Country {}".format(country))

Country Algeria
Country Angola
Country Argentina
Country Australia
Country Austria
Country Bahamas
Country Bangladesh
Country Belarus
Country Belgium
Country Bhutan
Country Brazil
Country Bulgaria
Country Cambodia
Country Cameroon
Country Chile
Country China
Country Colombia
Country Cyprus
Country Denmark
Country El Salvador
Country Estonia
Country Ethiopia
Country Fiji
Country Finland
Country France
Country Georgia
Country Ghana
Country Grenada
Country Guinea
Country Haiti
Country Honduras
Country Hungary
Country India
Country Indonesia
Country Ireland
Country Italy
Country Japan
Country Kenya
Country South Korea
Country Liberia
Country Malaysia
Country Mexico
Country Morocco
Country Nepal
Country New Zealand
Country Norway
Country Pakistan
Country Peru
Country Qatar
Country Russia
Country Singapore
Country South Africa
Country Spain
Country Sweden
Country Switzerland
Country Thailand
Country United Arab Emirates
Country United Kingdom
Country United States
Country Uruguay
Country Ven

In [192]:
len(countries)

63

In [203]:
for i in range(len(countries)):
  country = countries[i]
  GDPperCapita = GPC[i]
  print("No. {} {} has GDP per capita of US$ {}!".format(i+1, country,GDPperCapita) )

No. 1 Algeria has GDP per capita of US$ 2255.225482!
No. 2 Angola has GDP per capita of US$ 629.9553062!
No. 3 Argentina has GDP per capita of US$ 11601.63022!
No. 4 Australia has GDP per capita of US$ 25306.82494!
No. 5 Austria has GDP per capita of US$ 27266.40335!
No. 6 Bahamas has GDP per capita of US$ 19466.99052!
No. 7 Bangladesh has GDP per capita of US$ 588.3691778!
No. 8 Belarus has GDP per capita of US$ 2890.345675!
No. 9 Belgium has GDP per capita of US$ 24733.62696!
No. 10 Bhutan has GDP per capita of US$ 1445.760002!
No. 11 Brazil has GDP per capita of US$ 4803.398244!
No. 12 Bulgaria has GDP per capita of US$ 2618.876037!
No. 13 Cambodia has GDP per capita of US$ 590.4521124!
No. 14 Cameroon has GDP per capita of US$ 665.7982328!
No. 15 Chile has GDP per capita of US$ 7122.938458!
No. 16 China has GDP per capita of US$ 2639.54156!
No. 17 Colombia has GDP per capita of US$ 3362.4656!
No. 18 Cyprus has GDP per capita of US$ 15378.16704!
No. 19 Denmark has GDP per capita of 

In [194]:
import openpyxl

In [195]:
file_path = "/content/Olympic 2012 Medal Tally.xlsx"


# New Section

In [196]:
pd.read_excel(file_path)

Unnamed: 0     Unnamed: 1    Unnamed: 2 Unnamed: 3   Unnamed: 4 Unnamed: 5  \
0         NaN        Country  Country Code       Year  Medal Tally        NaN   
1         NaN            NaN           NaN        NaN         Gold     Silver   
2         NaN  Great Britain           GBR       2012           29         17   
3         NaN         China            CHN       2012           38         28   
4         NaN         Russia           RUS       2012           24         25   
5         NaN  United States            US       2012           46         28   
6         NaN          Korea           KOR       2012           13          8   
7         NaN          Japan           JPN       2012            7         14   
8         NaN        Germany           GER       2012           11         11   

  Unnamed: 6  
0        NaN  
1     Bronze  
2         19  
3         22  
4         32  
5         29  
6          7  
7         17  
8         14

In [197]:
import yfinance as yf

In [204]:
data = yf.download("BB", start='2022-1-1', end = '2024-3-22')

[*********************100%%**********************]  1 of 1 completed


In [205]:
data.to_excel("BB.xlsx")

In [206]:
pd.read_excel("BB.xlsx")

Date  Open  High   Low  Close  Adj Close    Volume
0   2022-01-03  9.32  9.39  9.10   9.37       9.37   5074700
1   2022-01-04  9.37  9.49  9.12   9.33       9.33   6166400
2   2022-01-05  9.27  9.35  8.78   8.78       8.78   9432700
3   2022-01-06  8.79  9.02  8.47   8.78       8.78  11285300
4   2022-01-07  8.97  9.23  8.80   8.86       8.86   6329700
..         ...   ...   ...   ...    ...        ...       ...
552 2024-03-15  3.06  3.08  2.76   2.85       2.85  41895900
553 2024-03-18  2.87  2.88  2.63   2.65       2.65   8566100
554 2024-03-19  2.64  2.64  2.46   2.47       2.47  15011900
555 2024-03-20  2.53  2.64  2.48   2.62       2.62  16241500
556 2024-03-21  2.64  2.83  2.64   2.78       2.78  12281600

[557 rows x 7 columns]

In [201]:
data["Close"].describe()

count     549.000000
mean     4157.641354
std       297.091679
min      3442.500000
25%      3883.250000
50%      4191.049805
75%      4373.899902
max      5100.600098
Name: Close, dtype: float64

In [202]:
pd.read_excel("/content/can_lang.xlsx")

category                        language  \
0                       Aboriginal languages    Aboriginal languages, n.o.s.   
1    Non-Official & Non-Aboriginal languages                       Afrikaans   
2    Non-Official & Non-Aboriginal languages  Afro-Asiatic languages, n.i.e.   
3    Non-Official & Non-Aboriginal languages                      Akan (Twi)   
4    Non-Official & Non-Aboriginal languages                        Albanian   
..                                       ...                             ...   
209  Non-Official & Non-Aboriginal languages                           Wolof   
210                     Aboriginal languages                      Woods Cree   
211  Non-Official & Non-Aboriginal languages               Wu (Shanghainese)   
212  Non-Official & Non-Aboriginal languages                         Yiddish   
213  Non-Official & Non-Aboriginal languages                          Yoruba   

     mother_tongue  most_at_home  most_at_work  lang_known  
0              590           235            30         665  
1            10260          4785            85       23415  
2             1150           445            10        2775  
3            13460          5985            25       22150  
4            26895         13135           345       31930  
..             ...           ...           ...         ...  
209           3990          1385            10        8240  
210           1840           800            75        2665  
211          12915          7650           105       16530  
212          13555          7085           895       20985  
213           9080          2615            15       22415  

[214 rows x 6 columns]