<a href="https://colab.research.google.com/github/Menon-Vineet/Python-Basics-Simpli-/blob/main/Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
def add2(a,b):
    return a+b

In [3]:
a=1.2
b=3.5
add2(a,b)


4.7

In [4]:
w = "Vineet"

In [8]:
"et" in w

True

In [9]:
q=(1,2,)

In [10]:
q=q*2

In [11]:
q

(1, 2, 1, 2)

In [12]:
def p():
  q=1
  w=2
  return q,w

In [14]:
p()

(1, 2)

In [16]:
s=("q","w",'e')

In [21]:
for position, name in enumerate(s):
  print (position+1, name)

1 q
2 w
3 e


In [22]:
sorted ("Vineet Menon")

[' ', 'M', 'V', 'e', 'e', 'e', 'i', 'n', 'n', 'n', 'o', 't']

In [35]:
Score = 50

In [38]:
if Score>90:
  print ("Grade A")
elif (90>=Score>=50):
  print ('Grade B')
else:
  print ("Fail")

Grade B


In [9]:
import numpy as np
ar = np.zeros((4,4))

In [10]:
ar

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
print (ar)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
ara = np.arange(4)

In [13]:
ara

array([0, 1, 2, 3])

In [15]:
arr = np.linspace(1,6,5)

In [16]:
arr

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

In [27]:
td = np.arange(27).reshape(3,3,3)

In [28]:
td

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [29]:
td.ndim

3

In [31]:
td.shape

(3, 3, 3)

In [32]:
td.size

27

In [36]:
td.dtype

dtype('int64')